# Configuration always using underscore, since YAML is not obey anything.
# I just create my own standard to use camelCase.
# https://stackoverflow.com/a/42548827/5489910

# settings for Transport layer
transport:
  http:
    port: 1234

# dependencies connection
# note that key must be alphanumeric only, e.g: db1, postgres1, mysql1
## define all database connection at once
## If you use the same database for different services, the connection pool will be shared
databaseResources:
  allInOneDB:
    disable: false
    driver: "postgres"
    postgres:
      debug: true
      dsn: "user=postgres password=postgres host=localhost port=5433 dbname=ngendika sslmode=disable" # Data Source Name

services:
  # settings each repository, select based on dependencies connection
  ## appstore to save application information
  app:
    dbLabel: allInOneDB # refer to databaseResources

  serviceProvider:
    dbLabel: allInOneDB # refer to databaseResources

  messaging:
    maxBuffer: 100
    maxParallel: 10 # number of semaphore to limit the number of goroutines working on parallel tasks
