# Configuration always using underscore, since YAML is not obey anything.
# I just create my own standard to use camelCase.
# https://stackoverflow.com/a/42548827/5489910

# settings for Transport layer
transport:
  http:
    port: 1234

# dependencies connection
# note that key must be alphanumeric only, e.g: db1, postgre1, mysql1
## define all database connection at once
database:
  db1:
    disable: false
    debug: true
    driver: "postgres"
    dsn: "user=postgres password=postgres host=localhost port=5432 dbname=ngendika sslmode=disable" # Data Source Name

# settings each repository, select based on dependencies connection
## appstore to save application information
appRepo:
  database: db1 # refer to database

fcmRepo:
  database: db1 # refer to database

msgRepo:
  database: db1 # refer to database

## service
msgService:
  maxParallel: 10 # number of semaphore to limit the number of goroutines working on parallel tasks
