# MY_IP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p') docker-compose up --remove-orphan
version: '3.5'

services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5433:5432
    networks:
      - danbam-network
    environment:
      - POSTGRES_USER=danbam
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=danbam
    volumes:
      - ./logs:/var/lib/postgresql/data

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      - danbam-network

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    networks:
      - danbam-network
    depends_on:
      - zookeeper
    environment:
      KAFKA_CREATE_TOPICS: "pn:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: ${MY_IP} # docker-machine ip
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

networks:
  danbam-network:
    name: danbam-network