# MY_IP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p') docker-compose up --remove-orphan
version: '3.5'

services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5433:5432"
    networks:
      - ngendika-network
    environment:
      - POSTGRES_USER=danbam
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=danbam
    volumes:
      - ./logs/postgres_data:/var/lib/postgresql/data


networks:
  ngendika-network:
    name: ngendika-network